### ISSUE TITLE
[Question] There is something wrong with the Documentation. 

### ISSUE THREAD

**Issue by ZhHe11** [PKU-Alignment/safety-gymnasium#110]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [x] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Questions

There is something wrong with the Documentation. I cannot access the link(https://www.safety-gymnasium.com/).

**Comment by muchvo** [comment]
[This discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/104) may help you.
