### ISSUE TITLE
[Question] how to change the step of truncation 

### ISSUE THREAD

**Issue by JoeyWu99** [PKU-Alignment/safety-gymnasium#113]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Questions

Hi，I'm a new beginner of the safety_gymnasium. I want to change the step of truncation.
I'm trying to change with this code:
```
from safety_gymnasium.wrappers import SafeTimeLimit
env = SafeTimeLimit(env, max_episode_steps=1000)
```
However, It doesn't seem to be working. Is there any solution?

**Comment by muchvo** [comment]
You can change this [here](https://github.com/PKU-Alignment/safety-gymnasium/blob/main/safety_gymnasium/__init__.py), because we predefined a `TimeLimitWrapper` for each env.

**Comment by JoeyWu99** [comment]
Thank you for your reply.
I tried to change the 'SafetyPointRace0-v0' environment by changing ‘500’ to ‘1000’ in line #188 of the __init__.py. :
`__combine(race_tasks, robots, max_episode_steps=1000)`
When I tested it I found that the env._max_episode_steps did change to 1000, but it was still truncated at 500 steps.

**Comment by muchvo** [comment]
Sorry for overlooking [that part](https://github.com/PKU-Alignment/safety-gymnasium/blob/main/safety_gymnasium/tasks/safe_vision/race/race_level0.py#L28-L29). We've realized that there are two design aspects that need modification, which are not quite ideal at the moment. We plan to address these in an upcoming release.
