### ISSUE TITLE
[Question] What's meaning of lidar ?(in low-dimension input tasks)

### ISSUE THREAD

**Issue by liushaohuai5** [PKU-Alignment/safety-gymnasium#116]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Questions

I want to understand what the lidar exactly means. It seems like some elements of the hazard lidar vector will increase if approaching the hazard area. And what are the meanings of Min, Max, Max distance?
![Weixin Screenshot_20240417112300](https://github.com/PKU-Alignment/safety-gymnasium/assets/45538886/da3ed1ec-dfe5-480a-bb67-bbf1652c0f97)

**Comment by muchvo** [comment]
Hello, please refer to [this section](https://safety-gymnasium.readthedocs.io/en/latest/components_of_environments/objects.html#pseudo-lidar) of the documentation for more details.

**Comment by liushaohuai5** [comment]
It was weird in SafePointGoal1. As you mentioned the max_dist=3, so the O_i is calculated by D_i/D_max. However, I observed multiple 0 in cost_obs (obs[-32:-16]) without entering hazard areas. It seems that O_i is calculated by exp(-\alpha D_i).
![Weixin Screenshot_20240417112300](https://github.com/PKU-Alignment/safety-gymnasium/assets/45538886/4921cbac-563c-4ee6-b9a1-9d4b08423da0)

**Comment by muchvo** [comment]
When an object exceeds the maximum detection range of the lidar, it becomes undetectable and is therefore recorded as zero. This is [the code](https://github.com/PKU-Alignment/safety-gymnasium/blob/main/safety_gymnasium/bases/base_task.py#L518) of this mechanism.
