### ISSUE TITLE
Can Safety-Gymnasium run on the SSH Server[Question] 

### ISSUE THREAD

**Issue by SimonZhan-code** [PKU-Alignment/safety-gymnasium#68]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Questions

Hi, a quick question does safety-gymnasium have to run in the local environment? Can we run it on the SSH Server? 

I'm having the following bug report from glfw package running the toy example provided in the **example** folder on the SSH server:
`.local/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: Failed to open display :0.0'`
`.local/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'`
`python: /builds/florianrhiem/pyGLFW/glfw-3.3.8/src/monitor.c:445: glfwGetVideoMode: Assertion 'monitor != ((void *)0)' failed.
Aborted (core dumped)`

Or, is there any way we can bypass the GUI initiation and run the safety-gymnasium GUI-free?

**Comment by muchvo** [comment]
Yes, simply change render mode to anything except 'human'.
