### ISSUE TITLE
[Question] How to get the reward and cost design for each environment?

### ISSUE THREAD

**Issue by Chenrf1121** [PKU-Alignment/safety-gymnasium#91]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Questions

I am curious about the rewards and costs in tasks. I want to know when the adding rewards will be triggered and when the costs will be increased. Which file should I check? Like "SafetyPointGoal1-v0"

**Comment by muchvo** [comment]
You can refer to [this link](https://github.com/PKU-Alignment/safety-gymnasium/blob/main/safety_gymnasium/builder.py#L209C29-L209C29) for a more detailed understanding. Essentially, the task is associated with the `Builder` class. The `Builder` class constructs a standard process framework for some tasks, enabling fixed behaviors to be triggered. Therefore, you can understand that when `safety_gymnaisum.make` is called, it returns an object of the `Builder` class, which contains a class related to the task.
