### ISSUE TITLE
[Question] How to efficiently design a custom navigation environment?

### ISSUE THREAD

**Issue by aivarsoo** [PKU-Alignment/safety-gymnasium#96]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [x] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Questions

Hello,

I am trying to create a simple custom goal environment. I manage to come up with the following code to make an environment 
```python
from __future__ import annotations

from typing import Dict
import safety_gymnasium
from safety_gymnasium.assets.geoms import Goal
from safety_gymnasium.assets.geoms import Hazards
from safety_gymnasium.agents.point import Point
from safety_gymnasium.agents.car import Car
from safety_gymnasium.bases.base_task import BaseTask
from safety_gymnasium.builder import Builder
from safety_gymnasium.utils.task_utils import get_task_class_name

agents = {
    "point": Point,
    "car": Car,
}
        
class SimpleGoalLevel1(BaseTask):
    """
    Custom safety gym environment
    """
    def __init__(
        self, 
        config:Dict=dict(),
    ):
        super(SimpleGoalLevel1, self).__init__(config=config)
        # Increased difficulty and randomization
        self.placements_conf.extents = [-1.5, -1.5, 1.5, 1.5]

        # Instantiate and register hazards
        self._add_geoms(Hazards(
            num=1,
            size=0.7,
            locations=[(0,0)],
            is_lidar_observed=True,
            is_constrained=True,
            keepout=0.705))

        # Instantiate and register the goal
        self._add_geoms(Goal(
            keepout=0.305, 
            size=0.3, 
            locations=[(1.1, 1.1)],
            is_lidar_observed=True))
        
        self.lidar_conf.max_dist = 3
        self.lidar_conf.num_bins = 16
        
        self.last_dist_goal = None
    
    def _build_agent(self, agent_name:str) -> None:
        if agent_name in agents:
            self.agent = agents[agent_name](random_generator=self.random_generator)
        else:
            super()._build_agent(agent_name=agent_name)
         
    def calculate_reward(self):
        """Determine reward depending on the agent and tasks."""
        # pylint: disable=no-member
        reward = 0.0
        dist_goal = self.dist_goal()
        reward += (self.last_dist_goal - dist_goal) * self.goal.reward_distance
        self.last_dist_goal = dist_goal

        if self.goal_achieved:
            reward += self.goal.reward_goal

        return reward
            
    def specific_reset(self):
        pass

    def specific_step(self):
        pass

    def update_world(self):
        """Build a new goal position, maybe with resampling due to hazards."""
        self.build_goal_position()
        self.last_dist_goal = self.dist_goal()

    @property
    def goal_achieved(self):
        """Whether the goal of task is achieved."""
        # pylint: disable-next=no-member
        return self.dist_goal() <= self.goal.size

tasks = {
    "SimpleGoalLevel1": SimpleGoalLevel1
}

class CustomBuilder(Builder):
   def _get_task(self):
        class_name = get_task_class_name(self.task_id)
        if class_name in tasks:
            task_class = tasks[class_name]
            task = task_class(config=self.config)
            task.build_observation_space()
        else:
            task = super()._get_task()    
        return task

if __name__ == "__main__":
    env = CustomBuilder(task_id="SafetyPointSimpleGoal1-v0",
                        config={"agent_name":"point"})
    s, i = env.reset()
    env = safety_gymnasium.wrappers.SafetyGymnasium2Gymnasium(env)
    for k in range(1000):
        s, a, d, t, i = env.step(env.action_space.sample())
```
But it feels as a very complicated way to make an environment and I had to a few hacks to make it work. Some parts of the code I'd like to avoid. For example, 

1. Overloading the method `_build_agent`. If this is not done then the following error is thrown.
```python
  File "/miniconda3/envs/ray/lib/python3.8/site-packages/safety_gymnasium/bases/underlying.py", line 227, in __init__
    self._build_agent(self.agent_name)
  File "/miniconda3/envs/ray/lib/python3.8/site-packages/safety_gymnasium/bases/underlying.py", line 251, in _build_agent
    self.agent = agent_cls(random_generator=self.random_generator)
TypeError: 'module' object is not callable
```
2. To pass the task to the environment, I am creating a subclass of the `Builder` class with the overloaded `_get_task` method
3. When I create the environment I have to send the robot name in the config dictionary and in the `task_id`, that is: `env = CustomBuilder(task_id="SafetyPointSimpleGoal1-v0", config={"agent_name":"point"})`

I have the following questions:
1. Can this solution be simplified?
2. Why the error above is thrown if the method `_build_agent` is not overloaded?
3. Can the overloaded task be passed to the builder without inheritance? 
4. Why the agent needs to be specified twice: in the `task_id` and in the `config`

Thanks in advance!

**Comment by muchvo** [comment]
1. I'm quite impressed by the way you've created a new task; it's quite different from the design path we envisioned. We may need to consider adding more tutorials on how to customize tasks in our documentation. This enhancement will be implemented in future versions. For creating new tasks, you can define a class following the pattern of our [original task definitions](https://github1s.com/PKU-Alignment/safety-gymnasium/blob/HEAD/safety_gymnasium/tasks/safe_navigation/goal/goal_level0.py) and then register it with safety-gymnasium using the [appropriate method](https://github1s.com/PKU-Alignment/safety-gymnasium/blob/HEAD/safety_gymnasium/__init__.py) and import your task [here](https://github1s.com/PKU-Alignment/safety-gymnasium/blob/HEAD/safety_gymnasium/tasks/__init__.py). This way, you'll be able to `make` the task [directly from safety-gymnasium](https://github1s.com/PKU-Alignment/safety-gymnasium/blob/HEAD/examples/env.py).
2. I believe the error you're encountering would be resolved once you use our provided registration method for tasks. You might want to look into that [section of the code](https://github1s.com/PKU-Alignment/safety-gymnasium/blob/HEAD/safety_gymnasium/__init__.py) for clarity.
3. Yes, I've noticed you're looking to modify certain aspects of the `goal` task. In that case, you might find it easier to directly modify the source code of the original [goal task](https://github1s.com/PKU-Alignment/safety-gymnasium/blob/HEAD/safety_gymnasium/tasks/safe_navigation/goal/goal_level0.py), which should simplify the process considerably.
4. The reason for the issue you’re experiencing is similar to the second point. Ensuring that tasks are registered properly using our method should address the problem.

If you continue to face difficulties, don't hesitate to reach out for further assistance.

**Comment by aivarsoo** [comment]
Thank you for a quick response! It cleared up some confusion and some bugs on my side.

I have just one question left. It's still not clear to me how to register the custom task (in my case `SimpleGoalLevel1` class) so that the `Builder` class can pick it up. It seems that it reads only the tasks that are specified in the core `safety_gymnasium` [here](https://github.com/PKU-Alignment/safety-gymnasium/blob/main/safety_gymnasium/builder.py#L145):
```python
    from safety_gymnasium import tasks

    def _get_task(self) -> BaseTask:
        """Instantiate a task object."""
        class_name = get_task_class_name(self.task_id)
        assert hasattr(tasks, class_name), f'Task={class_name} not implemented.'
        task_class = getattr(tasks, class_name)
        task = task_class(config=self.config)

        task.build_observation_space()
        return task
```

This is the reason for the creation of the `CustomBuilder` class as I don't want to make modifications to the `safety_gymnasium` core, but happy to iterate on a PR, if necessary.

My current solution is:
```python
from __future__ import annotations

from typing import Dict
import safety_gymnasium
from safety_gymnasium.assets.geoms import Goal
from safety_gymnasium.assets.geoms import Hazards
from safety_gymnasium.bases.base_task import BaseTask
from safety_gymnasium.builder import Builder
from safety_gymnasium.utils.task_utils import get_task_class_name
        
class SimpleGoalLevel1(BaseTask):
    """
    Custom safety gym environment
    """
    def __init__(
        self, 
        config:Dict=dict(),
    ):
        super(SimpleGoalLevel1, self).__init__(config=config)

        self.placements_conf.extents = [-1.5, -1.5, 1.5, 1.5]

        # Instantiate and register hazards
        self._add_geoms(Hazards(
            num=1,
            size=0.7,
            locations=[(0,0)],
            is_lidar_observed=True,
            is_constrained=True,
            keepout=0.705))

        # Instantiate and register the goal
        self._add_geoms(Goal(
            keepout=0.305, 
            size=0.3, 
            locations=[(1.1, 1.1)],
            is_lidar_observed=True))
        
        self.lidar_conf.max_dist = 3
        self.lidar_conf.num_bins = 16
        
        self.last_dist_goal = None
           
    def calculate_reward(self):
        """Determine reward depending on the agent and tasks."""
        # pylint: disable=no-member
        reward = 0.0
        dist_goal = self.dist_goal()
        reward += (self.last_dist_goal - dist_goal) * self.goal.reward_distance
        self.last_dist_goal = dist_goal

        if self.goal_achieved:
            reward += self.goal.reward_goal

        return reward
            
    def specific_reset(self):
        pass

    def specific_step(self):
        pass

    def update_world(self):
        """Build a new goal position, maybe with resampling due to hazards."""
        self.build_goal_position()
        self.last_dist_goal = self.dist_goal()

    @property
    def goal_achieved(self):
        """Whether the goal of task is achieved."""
        # pylint: disable-next=no-member
        return self.dist_goal() <= self.goal.size

tasks = {
    "SimpleGoalLevel1": SimpleGoalLevel1
}

class CustomBuilder(Builder):
   def _get_task(self):
        class_name = get_task_class_name(self.task_id)
        if class_name in tasks:
            task_class = tasks[class_name]
            task = task_class(config=self.config)
            task.build_observation_space()
        else:
            task = super()._get_task()    
        return task

from safety_gymnasium import __register_helper

if __name__ == "__main__":
    env_id = "SafetyPointSimpleGoal1-v0" 
    max_episode_steps = 1000
    config = {'agent_name': "Point"}
    __register_helper(
        env_id=env_id,
        entry_point='custom_point_goal:CustomBuilder',
        spec_kwargs={'config': config, 'task_id': env_id},
        max_episode_steps=max_episode_steps,
    )

    env = safety_gymnasium.make(env_id)
    s, i = env.reset()
    env = safety_gymnasium.wrappers.SafetyGymnasium2Gymnasium(env)
    for k in range(1000):
        s, a, d, t, i = env.step(env.action_space.sample())
```

**Comment by muchvo** [comment]
That's a great question. Currently, we accomplish this by importing your task class in the corresponding `__init__.py` [file](https://github1s.com/PKU-Alignment/safety-gymnasium/blob/HEAD/safety_gymnasium/tasks/__init__.py). We plan to streamline this process in future versions by using decorators to automatically register classes to a container. Your solution is very good for the time being. If you're interested in contributing, we would be happy to discuss potential solutions with you in a Pull Request (PR).

**Comment by aivarsoo** [comment]
Thanks a lot for the response and the help in sorting this out!
