### ISSUE TITLE
[Feature Request] Creating a custom navigation task from the config dictionary similarly to the safety gym

### ISSUE THREAD

**Issue by aivarsoo** [PKU-Alignment/safety-gymnasium#98]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-Alignment/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/safety-gymnasium/discussions/new).

### Motivation

Motivated by the issue [#96](https://github.com/PKU-Alignment/safety-gymnasium/issues/96), I propose a feature similar to the original safety gym of making a custom navigation environment purely from the config file. In this case, the hazards, the vases, the goals etc can be specified in the config file. For example, to specify a simple goal environment with one large hazard the config should look like:
```python
    config = {
        'task_name': 'Goal',
        'agent_name': "Point",
        "lidar_conf.max_dist": 3,
        "lidar_conf.num_bins": 16,
        "placements_conf.extents": [-1.5, -1.5, 1.5, 1.5],
        "Hazards": dict(
            num=1,
            size=0.7,
            locations=[(0,0)],
            is_lidar_observed=True,
            is_constrained=True,
            keepout=0.705),
        "Goal": dict(
            keepout=0.305,
            size=0.3,
            locations=[(1.1, 1.1)],
            is_lidar_observed=True)
        }
```

While the environment is created through the make file while passing the config
```python
env_id = "SafetyCustomNavigation-v0"
env = safety_gymnasium.make(env_id, config=config)
```

I think this can be done for vision tasks as well.

### Solution

1. Introduce a custom level base class for all tasks. For example, for the task goal we can define:
```python
class GoalLevelC(BaseTask):
    """An agent must navigate to a goal."""

    def calculate_reward(self):
        """Determine reward depending on the agent and tasks."""
        # pylint: disable=no-member
        reward = 0.0
        dist_goal = self.dist_goal()
        reward += (self.last_dist_goal - dist_goal) * self.goal.reward_distance
        self.last_dist_goal = dist_goal

        if self.goal_achieved:
            reward += self.goal.reward_goal

        return reward

    def specific_reset(self):
        pass

    def specific_step(self):
        pass

    def update_world(self):
        """Build a new goal position, maybe with resampling due to hazards."""
        self.build_goal_position()
        self.last_dist_goal = self.dist_goal()

    @property
    def goal_achieved(self):
        """Whether the goal of task is achieved."""
        # pylint: disable-next=no-member
        return self.dist_goal() <= self.goal.size
```
Note the `__init__` method is not overloaded in this class.

2. The method `_parse`  in the class `Underlying`  can handle adding hazards, vases, gremlins and goals. For example, to handle hazards and goals we can modify the method to:
```python
    import safety_gymnasium.assets.geoms as geoms
    for key, value in config.items():
        if '.' in key:
            obj, key = key.split('.')
            assert hasattr(self, obj) and hasattr(getattr(self, obj), key), f'Bad key {key}'
            setattr(getattr(self, obj), key, value)
        elif hasattr(geoms, key):
            self._add_geoms(getattr(geoms, key)(**value))
        else:
            assert hasattr(self, key), f'Bad key {key}'
            setattr(self, key, value)
```

**Comment by muchvo** [comment]
Your proposal has the potential to make usage more straightforward, and I see the merit in implementing it. Would you be interested in joining our project as a contributor? We could collaborate on this feature through a pull request. I believe involving our users as contributors to collectively iterate from the user's perspective can provide valuable insights and guidance for the development of new features.

**Comment by aivarsoo** [comment]
I'll be happy to prepare a PR on this feature! You can assign it to me.
